version: '3'

services:
  api:
    build:
      context: .
      dockerfile: API/WebAPI/Dockerfile
    ports:
      - "5000:80"  # Port HTTP local pour l'API
      - "5001:443"  # Port HTTPS local pour l'API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_URL=http://api:5000

  front:
    build:
      context: ./FRONT/AmusementPark
      dockerfile: Dockerfile
    ports:
      - "4200:80"  # Port HTTP local pour le front-end
      - "4201:443"  # Port HTTPS local pour le front-end
    depends_on:
      - api
    environment:
      - API_URL=https://api:5001

networks:
  default:
  
  