version: '3'

services:
  api:
    container_name: amusement-park-api
    build:
      context: .
      dockerfile: API/WebAPI/Dockerfile
    ports:
      - "5000:80"  # Port HTTP local pour l'API
      - "5001:443"  # Port HTTPS local pour l'API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_URL=http://api:5000

  front:
    container_name: amusement-park-front
    build:
      context: ./FRONT/AmusementPark
      dockerfile: Dockerfile
    ports:
      - "4200:80"  # Port HTTP local pour le front-end
      - "4201:443"  # Port HTTPS local pour le front-end
    depends_on:
      - api
    environment:
      - API_URL=https://api:5001

  amusement-park-db:
    container_name: amusement-park-db
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - amusement_park_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - amusement-park-db
    ports:
      - "5050:80"

volumes:
  amusement_park_db_data:     

networks:
  default:
  
  