namespace AmusementPark.Application.Features.Seo.Handlers;

public sealed partial class GetPublicHtmlSitemapNodesQueryHandler
{
    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> SiteLabels =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["en"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["home"] = "Home",
                ["parks"] = "Parks",
                ["technical"] = "Technical pages",
                ["references"] = "References",
                ["rankings"] = "Rankings",
                ["ratingMethodology"] = "Ranking methodology",
                ["about"] = "About",
                ["contact"] = "Contact",
                ["versions"] = "Versions",
                ["privacy"] = "Privacy",
                ["sitemap"] = "Sitemap",
                ["park"] = "Park",
                ["interactiveMap"] = "Map",
                ["weather"] = "Weather",
                ["openingHours"] = "Opening hours",
                ["pricing"] = "Tickets and prices",
                ["images"] = "Images",
                ["videos"] = "Videos",
                ["zones"] = "Areas",
                ["items"] = "Attractions",
                ["history"] = "History",
                ["manufacturers"] = "Manufacturers",
                ["operators"] = "Operators",
                ["founders"] = "Founders",
            },
            ["fr"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["home"] = "Accueil",
                ["parks"] = "Parcs",
                ["technical"] = "Pages techniques",
                ["references"] = "Références",
                ["rankings"] = "Classements",
                ["ratingMethodology"] = "Méthodologie des classements",
                ["about"] = "À propos",
                ["contact"] = "Contact",
                ["versions"] = "Versions",
                ["privacy"] = "Confidentialité",
                ["sitemap"] = "Plan du site",
                ["park"] = "Parc",
                ["interactiveMap"] = "Carte",
                ["weather"] = "Météo",
                ["openingHours"] = "Horaires",
                ["pricing"] = "Tarifs et billets",
                ["images"] = "Images",
                ["videos"] = "Vidéos",
                ["zones"] = "Zones",
                ["items"] = "Attractions",
                ["history"] = "Histoire",
                ["manufacturers"] = "Constructeurs",
                ["operators"] = "Exploitants",
                ["founders"] = "Fondateurs",
            },
            ["de"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["home"] = "Startseite",
                ["parks"] = "Parks",
                ["technical"] = "Technische Seiten",
                ["references"] = "Referenzen",
                ["rankings"] = "Ranglisten",
                ["ratingMethodology"] = "Ranglisten-Methodik",
                ["about"] = "Über uns",
                ["contact"] = "Kontakt",
                ["versions"] = "Versionen",
                ["privacy"] = "Datenschutz",
                ["sitemap"] = "Sitemap",
                ["park"] = "Park",
                ["interactiveMap"] = "Karte",
                ["weather"] = "Wetter",
                ["openingHours"] = "Öffnungszeiten",
                ["pricing"] = "Preise und Tickets",
                ["images"] = "Bilder",
                ["videos"] = "Videos",
                ["zones"] = "Bereiche",
                ["items"] = "Attraktionen",
                ["history"] = "Geschichte",
                ["manufacturers"] = "Hersteller",
                ["operators"] = "Betreiber",
                ["founders"] = "Gründer",
            },
            ["es"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["home"] = "Inicio",
                ["parks"] = "Parques",
                ["technical"] = "Páginas técnicas",
                ["references"] = "Referencias",
                ["rankings"] = "Clasificaciones",
                ["ratingMethodology"] = "Metodología de las clasificaciones",
                ["about"] = "Acerca de",
                ["contact"] = "Contacto",
                ["versions"] = "Versiones",
                ["privacy"] = "Privacidad",
                ["sitemap"] = "Mapa del sitio",
                ["park"] = "Parque",
                ["interactiveMap"] = "Mapa",
                ["weather"] = "Tiempo",
                ["openingHours"] = "Horarios",
                ["pricing"] = "Tarifas y entradas",
                ["images"] = "Imágenes",
                ["videos"] = "Vídeos",
                ["zones"] = "Zonas",
                ["items"] = "Atracciones",
                ["history"] = "Historia",
                ["manufacturers"] = "Fabricantes",
                ["operators"] = "Operadores",
                ["founders"] = "Fundadores",
            },
            ["it"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["home"] = "Home",
                ["parks"] = "Parchi",
                ["technical"] = "Pagine tecniche",
                ["references"] = "Riferimenti",
                ["rankings"] = "Classifiche",
                ["ratingMethodology"] = "Metodologia delle classifiche",
                ["about"] = "Chi siamo",
                ["contact"] = "Contatto",
                ["versions"] = "Versioni",
                ["privacy"] = "Privacy",
                ["sitemap"] = "Mappa del sito",
                ["park"] = "Parco",
                ["interactiveMap"] = "Mappa",
                ["weather"] = "Meteo",
                ["openingHours"] = "Orari",
                ["pricing"] = "Tariffe e biglietti",
                ["images"] = "Immagini",
                ["videos"] = "Video",
                ["zones"] = "Zone",
                ["items"] = "Attrazioni",
                ["history"] = "Storia",
                ["manufacturers"] = "Costruttori",
                ["operators"] = "Operatori",
                ["founders"] = "Fondatori",
            },
            ["nl"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["home"] = "Home",
                ["parks"] = "Parken",
                ["technical"] = "Technische pagina's",
                ["references"] = "Referenties",
                ["rankings"] = "Ranglijsten",
                ["ratingMethodology"] = "Methodologie van ranglijsten",
                ["about"] = "Over ons",
                ["contact"] = "Contact",
                ["versions"] = "Versies",
                ["privacy"] = "Privacy",
                ["sitemap"] = "Sitemap",
                ["park"] = "Park",
                ["interactiveMap"] = "Kaart",
                ["weather"] = "Weer",
                ["openingHours"] = "Openingstijden",
                ["pricing"] = "Prijzen en tickets",
                ["images"] = "Afbeeldingen",
                ["videos"] = "Video's",
                ["zones"] = "Zones",
                ["items"] = "Attracties",
                ["history"] = "Geschiedenis",
                ["manufacturers"] = "Bouwers",
                ["operators"] = "Exploitanten",
                ["founders"] = "Oprichters",
            },
            ["pl"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["home"] = "Strona główna",
                ["parks"] = "Parki",
                ["technical"] = "Strony techniczne",
                ["references"] = "Referencje",
                ["rankings"] = "Rankingi",
                ["ratingMethodology"] = "Metodologia rankingów",
                ["about"] = "O nas",
                ["contact"] = "Kontakt",
                ["versions"] = "Wersje",
                ["privacy"] = "Prywatność",
                ["sitemap"] = "Mapa strony",
                ["park"] = "Park",
                ["interactiveMap"] = "Mapa",
                ["weather"] = "Pogoda",
                ["openingHours"] = "Godziny otwarcia",
                ["pricing"] = "Ceny i bilety",
                ["images"] = "Obrazy",
                ["videos"] = "Filmy",
                ["zones"] = "Strefy",
                ["items"] = "Atrakcje",
                ["history"] = "Historia",
                ["manufacturers"] = "Producenci",
                ["operators"] = "Operatorzy",
                ["founders"] = "Założyciele",
            },
            ["pt"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["home"] = "Início",
                ["parks"] = "Parques",
                ["technical"] = "Páginas técnicas",
                ["references"] = "Referências",
                ["rankings"] = "Classificações",
                ["ratingMethodology"] = "Metodologia das classificações",
                ["about"] = "Sobre",
                ["contact"] = "Contacto",
                ["versions"] = "Versões",
                ["privacy"] = "Privacidade",
                ["sitemap"] = "Mapa do site",
                ["park"] = "Parque",
                ["interactiveMap"] = "Mapa",
                ["weather"] = "Meteorologia",
                ["openingHours"] = "Horários",
                ["pricing"] = "Preços e bilhetes",
                ["images"] = "Imagens",
                ["videos"] = "Vídeos",
                ["zones"] = "Zonas",
                ["items"] = "Atrações",
                ["history"] = "História",
                ["manufacturers"] = "Fabricantes",
                ["operators"] = "Operadores",
                ["founders"] = "Fundadores",
            },
        };

    private static string Label(string language, string key)
    {
        if (SiteLabels.TryGetValue(language, out IReadOnlyDictionary<string, string>? labels)
            && labels.TryGetValue(key, out string? label))
        {
            return label;
        }

        return SiteLabels["en"].TryGetValue(key, out string? fallback) ? fallback : key;
    }
}
