#!/usr/bin/env bash
set -euo pipefail

output_file="${1:-deploy/.env.generated}"
mkdir -p "$(dirname "${output_file}")"

value_or_default() {
  local name="$1"
  local default_value="$2"
  local value="${!name:-}"

  if [ -n "${value}" ]; then
    printf '%s' "${value}"
  else
    printf '%s' "${default_value}"
  fi
}

write_line() {
  local name="$1"
  local value="$2"
  printf '%s=%s\n' "${name}" "${value}"
}

public_domain="$(value_or_default PUBLIC_DOMAIN 'amusement-parks.fun')"
public_base_url="$(value_or_default PUBLIC_BASE_URL "https://${public_domain}")"
public_www_base_url="$(value_or_default PUBLIC_WWW_BASE_URL "https://www.${public_domain}")"
public_http_port="$(value_or_default PUBLIC_HTTP_PORT '18080')"
minio_api_port="$(value_or_default MINIO_API_PORT '19000')"
minio_console_port="$(value_or_default MINIO_CONSOLE_PORT '19001')"
allowed_hosts="$(value_or_default ALLOWED_HOSTS "${public_domain};www.${public_domain};localhost;127.0.0.1;amusementpark-api")"
forwarded_allowed_hosts="$(value_or_default FORWARDED_HEADERS_ALLOWED_HOSTS "${public_domain};www.${public_domain};localhost;127.0.0.1")"
ssr_allowed_hosts="$(value_or_default SSR_ALLOWED_HOSTS "${public_domain};www.${public_domain};localhost;127.0.0.1")"

{
  write_line COMPOSE_PROJECT_NAME "$(value_or_default COMPOSE_PROJECT_NAME 'amusementpark')"
  write_line API_IMAGE "${API_IMAGE:?API_IMAGE is required}"
  write_line FRONT_IMAGE "${FRONT_IMAGE:?FRONT_IMAGE is required}"
  write_line PUBLIC_HTTP_PORT "${public_http_port}"
  write_line PUBLIC_DOMAIN "${public_domain}"
  write_line PUBLIC_BASE_URL "${public_base_url}"
  write_line PUBLIC_WWW_BASE_URL "${public_www_base_url}"
  write_line PUBLIC_EDGE_SUBNET "$(value_or_default PUBLIC_EDGE_SUBNET '172.30.30.0/24')"
  write_line BACKEND_PRIVATE_SUBNET "$(value_or_default BACKEND_PRIVATE_SUBNET '172.30.31.0/24')"
  write_line ALLOWED_HOSTS "${allowed_hosts}"
  write_line FORWARDED_HEADERS_ALLOWED_HOSTS "${forwarded_allowed_hosts}"
  write_line FORWARDED_HEADERS_KNOWN_NETWORKS "$(value_or_default FORWARDED_HEADERS_KNOWN_NETWORKS '172.30.31.0/24')"
  write_line FORWARDED_HEADERS_FORWARD_LIMIT "$(value_or_default FORWARDED_HEADERS_FORWARD_LIMIT '2')"
  write_line FRONT_SSR_API_INTERNAL_URL "$(value_or_default FRONT_SSR_API_INTERNAL_URL 'http://api:8080')"
  write_line SSR_ALLOWED_HOSTS "${ssr_allowed_hosts}"
  write_line SSR_FORCE_HTTPS "$(value_or_default SSR_FORCE_HTTPS 'true')"
  write_line SSR_CSP_ALLOW_LOCAL_DEV_SOURCES "$(value_or_default SSR_CSP_ALLOW_LOCAL_DEV_SOURCES 'false')"
  write_line CSP_ENABLED "$(value_or_default CSP_ENABLED 'true')"
  write_line CSP_REPORT_ONLY "$(value_or_default CSP_REPORT_ONLY 'true')"
  write_line CSP_REPORT_URI "$(value_or_default CSP_REPORT_URI '/security/csp-report')"
  write_line FRONT_CSP_REPORT_URI "$(value_or_default FRONT_CSP_REPORT_URI '/api/security/csp-report')"
  write_line SEO_DEFAULT_LANGUAGE "$(value_or_default SEO_DEFAULT_LANGUAGE 'en')"
  write_line SEO_MAX_DYNAMIC_URLS_PER_TYPE "$(value_or_default SEO_MAX_DYNAMIC_URLS_PER_TYPE '50')"
  write_line AUTH_RATE_LIMIT_LOGIN_LIMIT "$(value_or_default AUTH_RATE_LIMIT_LOGIN_LIMIT '5')"
  write_line AUTH_RATE_LIMIT_LOGIN_WINDOW_SECONDS "$(value_or_default AUTH_RATE_LIMIT_LOGIN_WINDOW_SECONDS '60')"
  write_line AUTH_RATE_LIMIT_EXTERNAL_LOGIN_LIMIT "$(value_or_default AUTH_RATE_LIMIT_EXTERNAL_LOGIN_LIMIT '10')"
  write_line AUTH_RATE_LIMIT_EXTERNAL_LOGIN_WINDOW_SECONDS "$(value_or_default AUTH_RATE_LIMIT_EXTERNAL_LOGIN_WINDOW_SECONDS '60')"
  write_line AUTH_RATE_LIMIT_REFRESH_TOKEN_LIMIT "$(value_or_default AUTH_RATE_LIMIT_REFRESH_TOKEN_LIMIT '30')"
  write_line AUTH_RATE_LIMIT_REFRESH_TOKEN_WINDOW_SECONDS "$(value_or_default AUTH_RATE_LIMIT_REFRESH_TOKEN_WINDOW_SECONDS '60')"
  write_line AUTH_RATE_LIMIT_REGISTRATION_LIMIT "$(value_or_default AUTH_RATE_LIMIT_REGISTRATION_LIMIT '5')"
  write_line AUTH_RATE_LIMIT_REGISTRATION_WINDOW_SECONDS "$(value_or_default AUTH_RATE_LIMIT_REGISTRATION_WINDOW_SECONDS '900')"
  write_line AUTH_RATE_LIMIT_EMAIL_CHALLENGE_LIMIT "$(value_or_default AUTH_RATE_LIMIT_EMAIL_CHALLENGE_LIMIT '3')"
  write_line AUTH_RATE_LIMIT_EMAIL_CHALLENGE_WINDOW_SECONDS "$(value_or_default AUTH_RATE_LIMIT_EMAIL_CHALLENGE_WINDOW_SECONDS '900')"
  write_line AUTH_RATE_LIMIT_PASSWORD_RESET_LIMIT "$(value_or_default AUTH_RATE_LIMIT_PASSWORD_RESET_LIMIT '5')"
  write_line AUTH_RATE_LIMIT_PASSWORD_RESET_WINDOW_SECONDS "$(value_or_default AUTH_RATE_LIMIT_PASSWORD_RESET_WINDOW_SECONDS '900')"
  write_line ASPNETCORE_ENVIRONMENT "$(value_or_default ASPNETCORE_ENVIRONMENT 'Production')"
  write_line MONGO_DATABASE_NAME "$(value_or_default MONGO_DATABASE_NAME 'AmusementPark')"
  write_line MONGO_INITDB_ROOT_USERNAME "${MONGO_INITDB_ROOT_USERNAME:?MONGO_INITDB_ROOT_USERNAME is required}"
  write_line MONGO_INITDB_ROOT_PASSWORD "${MONGO_INITDB_ROOT_PASSWORD:?MONGO_INITDB_ROOT_PASSWORD is required}"
  write_line MONGO_APP_USERNAME "${MONGO_APP_USERNAME:?MONGO_APP_USERNAME is required}"
  write_line MONGO_APP_PASSWORD "${MONGO_APP_PASSWORD:?MONGO_APP_PASSWORD is required}"
  write_line MINIO_IMAGE "$(value_or_default MINIO_IMAGE 'quay.io/minio/minio:RELEASE.2025-07-23T15-54-02Z')"
  write_line MINIO_ROOT_USER "${MINIO_ROOT_USER:?MINIO_ROOT_USER is required}"
  write_line MINIO_ROOT_PASSWORD "${MINIO_ROOT_PASSWORD:?MINIO_ROOT_PASSWORD is required}"
  write_line MINIO_BUCKET "$(value_or_default MINIO_BUCKET 'amusement-park-images')"
  write_line MINIO_API_PORT "${minio_api_port}"
  write_line MINIO_CONSOLE_PORT "${minio_console_port}"
  write_line JWT_KEY "${JWT_KEY:?JWT_KEY is required}"
  write_line JWT_ISSUER "$(value_or_default JWT_ISSUER 'AmusementPark')"
  write_line JWT_AUDIENCE "$(value_or_default JWT_AUDIENCE 'AmusementPark')"
  write_line GOOGLE_CLIENT_ID "${GOOGLE_CLIENT_ID:?GOOGLE_CLIENT_ID is required}"
  write_line GOOGLE_CLIENT_SECRET "${GOOGLE_CLIENT_SECRET:?GOOGLE_CLIENT_SECRET is required}"
  write_line GOOGLE_REDIRECT_URI "$(value_or_default GOOGLE_REDIRECT_URI "${public_base_url%/}/api/auth/external/google/callback")"
  write_line FACEBOOK_APP_ID "$(value_or_default FACEBOOK_APP_ID '')"
  write_line FACEBOOK_APP_SECRET "$(value_or_default FACEBOOK_APP_SECRET '')"
  write_line EMAIL_MODE "$(value_or_default EMAIL_MODE 'Console')"
  write_line EMAIL_HOST "$(value_or_default EMAIL_HOST '')"
  write_line EMAIL_PORT "$(value_or_default EMAIL_PORT '587')"
  write_line EMAIL_USE_SSL "$(value_or_default EMAIL_USE_SSL 'false')"
  write_line EMAIL_USE_STARTTLS "$(value_or_default EMAIL_USE_STARTTLS 'true')"
  write_line EMAIL_USERNAME "$(value_or_default EMAIL_USERNAME '')"
  write_line EMAIL_PASSWORD "$(value_or_default EMAIL_PASSWORD '')"
  write_line EMAIL_FROM_ADDRESS "$(value_or_default EMAIL_FROM_ADDRESS "noreply@${public_domain}")"
  write_line EMAIL_FROM_NAME "$(value_or_default EMAIL_FROM_NAME 'Amusement Park')"
  write_line ADMIN_USER_ENABLED "$(value_or_default ADMIN_USER_ENABLED 'false')"
  write_line ADMIN_USER_EMAIL "$(value_or_default ADMIN_USER_EMAIL '')"
  write_line ADMIN_USER_PASSWORD "$(value_or_default ADMIN_USER_PASSWORD '')"
  write_line BACKUP_BEFORE_DEPLOY "$(value_or_default BACKUP_BEFORE_DEPLOY 'true')"
} > "${output_file}"

chmod 600 "${output_file}"
echo "Production environment file written to ${output_file}."
