export enum ImageCategory {
  AVATAR = 'AVATAR',
  LOGO = 'LOGO',
  PARK = 'PARK',
  PARK_ITEM = 'PARK_ITEM',
  OPERATOR = 'OPERATOR',
  MANUFACTURER = 'MANUFACTURER',
  FOUNDER = 'FOUNDER',
  VIDEO_THUMBNAIL = 'VIDEO_THUMBNAIL'
}
