export enum ImageCategory {
  AVATAR = 'AVATAR',
  PARK_LOGO = 'PARK_LOGO',
  PARK = 'PARK',
  ATTRACTION = 'ATTRACTION',
  OPERATOR = 'OPERATOR',
  MANUFACTURER = 'MANUFACTURER',
  FOUNDER = 'FOUNDER',
  VIDEO_THUMBNAIL = 'VIDEO_THUMBNAIL'
}
