export enum ImageOwnerType {
  NONE = 'NONE',
  PARK = 'PARK',
  USER = 'USER',
  PARK_ITEM = 'PARK_ITEM',
  PARK_OPERATOR = 'PARK_OPERATOR',
  ATTRACTION_MANUFACTURER = 'ATTRACTION_MANUFACTURER',
  PARK_FOUNDER = 'PARK_FOUNDER',
  VIDEO = 'VIDEO'
}
