import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { normalizeReleaseVersion, readConfiguredReleaseDocument } from './release-version-utils.mjs';

const fallbackVersion = 'v0.0.0-dev';
const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDirectory, '..');
const outputPath = resolve(projectRoot, 'src', 'environments', 'version.generated.ts');
const explicitVersion = process.env.SITE_VERSION?.trim();
const configuredReleaseDocument = readConfiguredReleaseDocument(projectRoot);
const configuredVersion = configuredReleaseDocument ? normalizeReleaseVersion(configuredReleaseDocument.version) : null;
const configuredReleaseHistory = normalizeReleaseHistory(configuredReleaseDocument?.history);

const version = explicitVersion || configuredVersion || readGitTagVersion() || fallbackVersion;
const source = explicitVersion
  ? 'SITE_VERSION'
  : configuredVersion
    ? 'release-version.json'
    : version === fallbackVersion
      ? 'fallback'
      : 'git tag';
const content = `// This file is generated by scripts/generate-version.mjs.\nexport interface ReleaseHistoryEntry {\n  readonly version: string;\n  readonly releasedAt: string;\n  readonly labels: Record<string, string>;\n}\n\nexport const siteVersion = ${JSON.stringify(version)};\nexport const releaseHistory: readonly ReleaseHistoryEntry[] = ${JSON.stringify(configuredReleaseHistory, null, 2)};\n`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, content, 'utf8');

console.log(`Generated ${relative(projectRoot, outputPath)} with site version "${version}" from ${source}.`);

function readGitTagVersion() {
  try {
    return execFileSync(
      'git',
      [
        '-c',
        `safe.directory=${projectRoot.replace(/\\/g, '/')}`,
        'describe',
        '--tags',
        '--abbrev=0'
      ],
      {
        cwd: projectRoot,
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'ignore']
      }
    ).trim();
  } catch {
    return null;
  }
}

function normalizeReleaseHistory(history) {
  if (!Array.isArray(history)) {
    return [];
  }

  return history.map((entry, index) => normalizeReleaseHistoryEntry(entry, index));
}

function normalizeReleaseHistoryEntry(entry, index) {
  if (!entry || typeof entry !== 'object') {
    throw new Error(`release-version.json history entry ${index} must be an object.`);
  }

  const version = normalizeReleaseVersion(entry.version);
  const releasedAt = typeof entry.releasedAt === 'string' ? entry.releasedAt.trim() : '';
  if (!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(releasedAt)) {
    throw new Error(`release-version.json history entry ${version} must have a YYYY-MM-DD releasedAt date.`);
  }

  if (!entry.labels || typeof entry.labels !== 'object' || Array.isArray(entry.labels)) {
    throw new Error(`release-version.json history entry ${version} must have localized labels.`);
  }

  return {
    version,
    releasedAt,
    labels: Object.fromEntries(Object.entries(entry.labels)
      .map(([language, label]) => [language.trim().toLowerCase(), typeof label === 'string' ? label.trim() : ''])
      .filter(([language, label]) => language.length === 2 && label.length > 0))
  };
}
