import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const fallbackVersion = 'v0.0.0-dev';
const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDirectory, '..');
const outputPath = resolve(projectRoot, 'src', 'environments', 'version.generated.ts');
const explicitVersion = process.env.SITE_VERSION?.trim();

const version = explicitVersion || readGitTagVersion() || fallbackVersion;
const source = explicitVersion ? 'SITE_VERSION' : version === fallbackVersion ? 'fallback' : 'git tag';
const content = `// This file is generated by scripts/generate-version.mjs.\nexport const siteVersion = ${JSON.stringify(version)};\n`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, content, 'utf8');

console.log(`Generated ${relative(projectRoot, outputPath)} with site version "${version}" from ${source}.`);

function readGitTagVersion() {
  try {
    return execFileSync(
      'git',
      [
        '-c',
        `safe.directory=${projectRoot.replace(/\\/g, '/')}`,
        'describe',
        '--tags',
        '--abbrev=0'
      ],
      {
        cwd: projectRoot,
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'ignore']
      }
    ).trim();
  } catch {
    return null;
  }
}
