export type ParkItemType =
  | 'RollerCoaster'
  | 'WaterRide'
  | 'FlatRide'
  | 'DarkRide'
  | 'FamilyRide'
  | 'ThrillRide'
  | 'AnimalExhibit'
  | 'Restaurant'
  | 'Snack'
  | 'Hotel'
  | 'Show'
  | 'Shop'
  | 'Service'
  | 'Transport'
  | 'Other';
