export enum VideoType {
  OTHER = 'OTHER',
  ON_RIDE = 'ON_RIDE',
  OFF_RIDE = 'OFF_RIDE',
  WALKTHROUGH = 'WALKTHROUGH',
  ADVERTISEMENT = 'ADVERTISEMENT',
  DOCUMENTARY = 'DOCUMENTARY',
  REVIEW = 'REVIEW',
  NEWS = 'NEWS',
  EVENT = 'EVENT',
  INTERVIEW = 'INTERVIEW'
}
